// resources/assets/js/components/Classificacao.vue
<template v-html="rawHtml">
  <div id="classificacao">
    <div class="col-sm-12 box">
      <div class="btn-group btn-rodada" role="group">
        <button
          type="button"
          class="btn btn-default"
          :disabled="rodada < 1"
          @click="getRanking(rodada - 1)"
        >
          <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
        </button>
        <div class="btn-group">
          <button
            type="button"
            class="btn btn-default dropdown-toggle"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <span v-if="rodada > 0">
              {{ rodada }}ª Rodada
              <span class="caret"></span>
            </span>
            <span v-else>
              Classificação Geral
              <span class="caret"></span>
            </span>
          </button>
          <div class="dropdown-menu dropdown-rodada">
            <div class="flex-container">
              <div class="flex-items" v-for="(n, key) in bolao.campeonato.qtd_rodadas" :key="key">
                <a class="dropdown-rodada-a" @click="getRanking(n)">{{ n }}ª</a>
              </div>
              <div class="flex-items geral">
                <a class="dropdown-rodada-a" @click="getRanking(0)">Geral</a>
              </div>
              <div class="flex-items geral">
                <a class="dropdown-rodada-a" @click="getRanking(0, 1)" style="padding: 0;">1º turno</a>
              </div>
              <div class="flex-items geral">
                <a class="dropdown-rodada-a" @click="getRanking(0, 2)" style="padding: 0;">2º turno</a>
              </div>
            </div>
          </div>
        </div>
        <button
          type="button"
          class="btn btn-default"
          :disabled="rodada >= bolao.campeonato.qtd_rodadas"
          @click="getRanking(rodada + 1);"
        >
          <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </button>
      </div>
    </div>
    <div class="col-sm-12 box" v-if="dataLoading">
      <i class="glyphicon glyphicon-refresh"></i> Loading...
    </div>
    <div class="col-sm-12 box" v-if="!dataLoading">
      <div class="col-sm-12 box" v-if="!user && participantes.length == 0">
        <div class="alert alert-danger">
          <p class="text-center">Não existe dados para listar!</p>
        </div>
      </div>
      <div class="col-sm-12 table-custom" v-else>
        <div class="row table-head">
          <div class="td">#</div>
          <div class="td">Participante</div>
          <div class="td">PG</div>
          <div class="td">PE</div>
          <div class="td">PV</div>
          <div class="td">DP</div>
        </div>
        <div
          class="row table-body"
          :class="{ 'bg-colors': rodada === 0 }"
          v-for="(participante, key) in participantes"
          :key="key"
        >
          <div class="td">{{ key + 1 }}º</div>
          <div class="td">{{ participante.name }}</div>
          <div class="td">{{ participante.pontosganhos }}</div>
          <div class="td">{{ participante.placarexato }}</div>
          <div class="td">{{ participante.placarvencedor }}</div>
          <div class="td">{{ participante.pontosganhos - participantes[0].pontosganhos }}</div>
        </div>
      </div>
    </div>
    <div class="col-sm-12 box" v-if="!dataLoading">
      <h4>
        <strong>Legenda</strong>
      </h4>
      <p>
        <strong>PG</strong> - Pontos Ganhos,
        <strong>PE</strong> - Placar Exato,
        <strong>PV</strong> - Placar Vencedor,
        <strong>DP</strong> - Diferença de pontos em relação ao primeiro colocado.
      </p>
      <p>
        <i class="glyphicon glyphicon-stop campeoes"></i> - Campeões,
        <i class="glyphicon glyphicon-stop lanternas"></i> - Lanternas.
      </p>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      user: this.data_user ? JSON.parse(this.data_user) : null,
      dataLoading: false,
      participantes: [],
      bolao: this.data_bolao ? JSON.parse(this.data_bolao) : null,
      rodada: 0,
    };
  },
  props: ["data_user", "data_bolao"],
  mounted() {
    this.getRanking(this.rodada);
  },
  methods: {
    getRanking(rodada, turno = 0) {
      this.dataLoading = true;
      this.rodada = rodada;
      this.$http
        .get("/api/participante/getRanking/" + rodada + "/" + turno)
        .then((response) => {
          this.participantes = response.data;
          this.dataLoading = false;
        })
        .catch((error) => {
          this.dataLoading = false;
          console.error("!Get Updated Data", error);
        });
    },
  },
};
</script>

// resources/js/Pages/Classificacao.jsx
import React, { useState } from "react";
import { Inertia } from "@inertiajs/inertia";
import { ArrowDownIcon, ArrowLeftIcon, ArrowRightIcon } from "../helpers";

const Classificacao = ({ bolao, participantes, rodada, turno }) => {
    const [dropdown, setDropdown] = useState(false);

    const handleRodada = (value) => {
        if (value >= 0) {
            setDropdown(false);
            Inertia.get(`/classificacao?rodada=${value}`);
        }
    };

    const handleSeason = (type) => {
        setDropdown(false);

        if (type >= 0) {
            Inertia.get(`/classificacao${type > 0 ? `?turno=${type}` : ""}`);
        }
    };

    return (
        <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg text-gray-600">
            {(participantes.length > 0 || rodada > 0 || turno > 0) && (
                <>
                    <div className={dropdown ? "vb-btn-group open" : "vb-btn-group"}>
                        <button onClick={() => handleRodada(+rodada - 1)} disabled={+rodada <= 1}>
                            {ArrowLeftIcon}
                        </button>
                        <button onClick={() => setDropdown(!dropdown)}>
                            <span className="flex items-center justify-center">
                                {turno && `${turno}º Turno`}
                                {rodada && `${rodada}ª Rodada`}
                                {!turno && !rodada && "Classificação Geral"}
                                {ArrowDownIcon}
                            </span>
                        </button>
                        <button onClick={() => handleRodada(+rodada + 1)} disabled={bolao.qtd_rodadas === +rodada}>
                            {ArrowRightIcon}
                        </button>
                    </div>

                    {dropdown && (
                        <div className="vb-dropdown">
                            <button className="col-span-4" onClick={() => handleSeason(0)}>
                                Geral
                            </button>
                            <button className="col-span-2" onClick={() => handleSeason(1)}>
                                1º turno
                            </button>
                            <button className="col-span-2" onClick={() => handleSeason(2)}>
                                2º turno
                            </button>

                            {[...Array(bolao.qtd_rodadas).keys()].map((item, key) => (
                                <button key={key} onClick={() => handleRodada(item + 1)}>
                                    {item + 1}ª
                                </button>
                            ))}
                        </div>
                    )}
                </>
            )}

            {participantes.length > 0 ? (
                <div className="p-3 sm:p-6 bg-white border-b border-gray-200">
                    <div className="flex flex-row border-b-2 py-2 font-bold bg-slate-800 text-white rounded-t-lg">
                        <div className="w-[10%] text-center">#</div>
                        <div className="w-[38%] truncate">Participante</div>
                        <div className="w-[14%] text-center">PG</div>
                        <div className="w-[12%] text-center">PE</div>
                        <div className="w-[12%] text-center">PV</div>
                        <div className="w-[14%] text-center">DP</div>
                    </div>

                    {participantes.map((participante, key) => (
                        <div
                            key={key}
                            id="classificacao"
                            className={`${!+rodada && key <= 2 && "vb-winners"} ${
                                !+rodada && key > participantes.length - 3 && "vb-losers"
                            }`}
                        >
                            <div className="w-[10%] text-center">
                                <span>{key + 1}º</span>
                            </div>
                            <div className="w-[38%] font-bold truncate">
                                <span>{participante.name}</span>
                            </div>
                            <div className="w-[14%] text-center font-bold">
                                <span>{participante.pontosganhos}</span>
                            </div>
                            <div className="w-[12%] text-center">
                                <span>{participante.placarexato}</span>
                            </div>
                            <div className="w-[12%] text-center">
                                <span>{participante.placarvencedor}</span>
                            </div>
                            <div className="w-[14%] text-center">
                                <span>{participante.pontosganhos - participantes[0].pontosganhos}</span>
                            </div>
                        </div>
                    ))}

                    <div className="pt-9">
                        <h4 className="font-bold text-lg pb-1">Legenda</h4>

                        <div className="flex items-center gap-1">
                            <span className="w-4 h-4 bg-green-900 border-[1px] border-gray-400" />
                            <p>- Ganhadores</p>
                        </div>

                        <div className="flex items-center gap-1">
                            <span className="w-4 h-4 bg-red-900 border-[1px] border-gray-400" />
                            <p>- Lanternas</p>
                        </div>

                        <div className="flex items-center gap-1">
                            <strong>PG</strong>
                            <p>- Pontos Ganhos</p>
                        </div>

                        <div className="flex items-center gap-1">
                            <strong>PE</strong>
                            <p>- Placar Exato</p>
                        </div>

                        <div className="flex items-center gap-1">
                            <strong>PV</strong>
                            <p>- Placar Vencedor</p>
                        </div>

                        <div className="flex items-center gap-1">
                            <strong>DP</strong>
                            <p>- Diferença de Pontos para o primeiro</p>
                        </div>
                    </div>
                </div>
            ) : (
                <div id="box-empty">Não existem dados para listar!</div>
            )}
        </div>
    );
};

export default Classificacao;
